/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ApiConfigService } from "../apiConfig.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApiConfigCreateInput } from "./ApiConfigCreateInput";
import { ApiConfig } from "./ApiConfig";
import { ApiConfigFindManyArgs } from "./ApiConfigFindManyArgs";
import { ApiConfigWhereUniqueInput } from "./ApiConfigWhereUniqueInput";
import { ApiConfigUpdateInput } from "./ApiConfigUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ApiConfigControllerBase {
  constructor(
    protected readonly service: ApiConfigService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ApiConfig })
  @nestAccessControl.UseRoles({
    resource: "ApiConfig",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createApiConfig(
    @common.Body() data: ApiConfigCreateInput
  ): Promise<ApiConfig> {
    return await this.service.createApiConfig({
      data: data,
      select: {
        apiKey: true,
        baseUrl: true,
        createdAt: true,
        endpoint: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ApiConfig] })
  @ApiNestedQuery(ApiConfigFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ApiConfig",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async apiConfigs(@common.Req() request: Request): Promise<ApiConfig[]> {
    const args = plainToClass(ApiConfigFindManyArgs, request.query);
    return this.service.apiConfigs({
      ...args,
      select: {
        apiKey: true,
        baseUrl: true,
        createdAt: true,
        endpoint: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ApiConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApiConfig",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async apiConfig(
    @common.Param() params: ApiConfigWhereUniqueInput
  ): Promise<ApiConfig | null> {
    const result = await this.service.apiConfig({
      where: params,
      select: {
        apiKey: true,
        baseUrl: true,
        createdAt: true,
        endpoint: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ApiConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApiConfig",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateApiConfig(
    @common.Param() params: ApiConfigWhereUniqueInput,
    @common.Body() data: ApiConfigUpdateInput
  ): Promise<ApiConfig | null> {
    try {
      return await this.service.updateApiConfig({
        where: params,
        data: data,
        select: {
          apiKey: true,
          baseUrl: true,
          createdAt: true,
          endpoint: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ApiConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApiConfig",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteApiConfig(
    @common.Param() params: ApiConfigWhereUniqueInput
  ): Promise<ApiConfig | null> {
    try {
      return await this.service.deleteApiConfig({
        where: params,
        select: {
          apiKey: true,
          baseUrl: true,
          createdAt: true,
          endpoint: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
